PREFIX ex: <http://duncan.org/resource/>
PREFIX prop: <http://duncan.org/property/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
  GRAPH <http://duncan.org/graph/can> {
    ex:bo_giao_duc_va_dao_tao wdt:P17 ex:viet_nam .
    ex:cologe wdt:P17 ex:chlb_duc .
    ex:itt wdt:P17 ex:chlb_duc .
    ex:ngoc_my wdt:P131 ex:huyen_quoc_oai .
    ex:nguoi wdt:P569 "1967-07-29"^^xsd:date .
    ex:nguoi wdt:P569 "Nam" .
    ex:nguoi_dang_ky wdt:P17 ex:tp_can_tho .
    ex:phong_2104_park_1_khu_do_thi_times_city_minh_khai_hoang_mai_ha_noi wdt:P131 ex:buu_dien .
    ex:phong_2104_park_1_khu_do_thi_times_city_minh_khai_hoang_mai_ha_noi wdt:P131 ex:home .
    ex:quang_tri_province wdt:P131 ex:thach_han_river_basin .
    ex:r_171_tay_son_dong_da_ha_noi wdt:P131 ex:dien_thoai_co_quan .
    ex:so_38_125_thuy_khue_tay_ho_ha_noi wdt:P131 ex:ha_noi .
    ex:so_38_125_thuy_khue_tay_ho_ha_noi wdt:P131 ex:so_38_125_thuy_khue .
    ex:so_38_125_thuy_khue_tay_ho_ha_noi wdt:P131 ex:tay_ho .
    ex:tham_nien_dao_tao wdt:P580 "6 năm" .
    ex:tran_van_ty wdt:P131 ex:khoa_cong_nghe_truong_dai_hoc_can_tho_khu_2_duong_3_2_phuong_xuan_khanh_quan_ninh_kieu_tp_can_tho .
    ex:tran_van_ty wdt:P131 ex:khu_2_duong_3_2_phuong_xuan_khanh_quan_ninh_kieu_tp_can_tho .
    ex:tran_van_ty wdt:P131 ex:nha_sole_10_khu_tap_the_dai_hoc_can_tho_khu_1_duong_30_4_phuong_hung_loi_quan_ninh_kieu_tp_can_tho .
    ex:tran_van_ty wdt:P131 ex:xa_long_tri_a_thi_xa_long_my_tinh_hau_giang .
    ex:tran_van_ty wdt:P19 ex:xa_long_tri_a_thi_xa_long_my_tinh_hau_giang .
    ex:tran_van_ty wdt:P569 "1979-02-10"^^xsd:date .
    ex:truong_dai_hoc wdt:P17 ex:viet_nam .
    ex:truong_dai_hoc_can_tho wdt:P131 "02923834267" .
    ex:truong_dai_hoc_khoa_hoc_ung_dung_cologne wdt:P17 ex:chlb_duc .
    ex:truong_dai_hoc_thuy_loi wdt:P17 ex:viet_nam .
    ex:vien_khoa_hoc_thuy_loi wdt:P580 "2002"^^xsd:gYear .
    ex:vien_khoa_hoc_thuy_loi_viet_nam wdt:P131 ex:nay .
    ex:vien_va_truong_dai_hoc_khoa_hoc_ung_dung_cologne wdt:P17 ex:chlb_duc .
    ex:vu_gia_thu_bon_river_basin wdt:P17 ex:vietnam .
    ex:wedc_international_conference wdt:P131 ex:hanoi .
    ex:world_friend_lan_thu_6 wdt:P17 ex:morocco .
  }
}
